version:  '3'
services:
  nginx:
    container_name: nginxdemo
    image: mdicky7/demonginx
    ports:
      - "80:80"
      - "7000:7000"
    volumes:
      - "./nginx:/var/www/html/"
    expose:
      - "7000"
